/**
 * Regenerates src/windows-zones.generated.ts from CLDR's windowsZones.xml.
 * Run with: npm run gen:windows-zones -w @w2msync/providers
 */
import { writeFile } from 'node:fs/promises';

const SOURCE =
  'https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml';

const xml = await (await fetch(SOURCE)).text();
const entries = [...xml.matchAll(/<mapZone other="([^"]+)" territory="001" type="([^"]+)"\s*\/>/g)]
  .map((m) => [m[1] as string, m[2] as string] as const)
  .sort(([a], [b]) => a.localeCompare(b));
if (entries.length < 100)
  throw new Error(`Only ${entries.length} zones found; did the format change?`);

const body = entries.map(
  ([windows, iana]) => `  ${JSON.stringify(windows)}: ${JSON.stringify(iana)},`,
);
await writeFile(
  new URL('../src/windows-zones.generated.ts', import.meta.url),
  `// Generated by scripts/gen-windows-zones.ts from Unicode CLDR windowsZones.xml (territory 001).
// CLDR data: Copyright © 1991-2026 Unicode, Inc. Unicode License v3, https://www.unicode.org/license.txt
export const WINDOWS_TO_IANA: Readonly<Record<string, string>> = {
${body.join('\n')}
};
`,
);
console.log(`Wrote ${entries.length} Windows → IANA zone mappings.`);
